/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Title = string;
export type Subtitle = string;
export type ImageURL = string;
/**
 * If true, the image upload will be used instead of the image URL
 */
export type UseImageUpload = boolean;

export interface InputData {
  title?: Title;
  subTitle?: Subtitle;
  imageUrl?: ImageURL;
  useUpload?: UseImageUpload;
  image?: UploadImageFile;
  [k: string]: unknown;
}
export interface UploadImageFile {
  [k: string]: unknown;
}
