/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Title = string;
export type Subtitle = string;
/**
 * If enabled, the image will stretch to fill the entire widget area. If disabled, the image will maintain its aspect ratio.
 */
export type StretchToFill = boolean;
/**
 * Display multiple images based on URLs in a list.
 */
export type MultiImage = boolean;
/**
 * The gap between images in pixels.
 */
export type Gap = number;
/**
 * Font size for the image label in pixels.
 */
export type ImageLabelFontSize = number;
export type ImageURL = string;
/**
 * If true, the image upload will be used instead of the image URL
 */
export type UseImageUpload = boolean;
/**
 * Unix timestamp in milliseconds for time-based filtering.
 */
export type Timestamp = number;
/**
 * This should be a valid URL string.
 */
export type ImageURL1 = string;
/**
 * Optionally provide a label for this image.
 */
export type ImageLabel = string;
/**
 * A list of image URLs to layout.
 */
export type Images = {
  timestamp?: Timestamp;
  imageUrl?: ImageURL1;
  label?: ImageLabel;
  [k: string]: unknown;
}[];

export interface InputData {
  title?: Title;
  subTitle?: Subtitle;
  stretchToFit?: StretchToFill;
  multiImage?: MultiImage;
  gap?: Gap;
  labelFontSize?: ImageLabelFontSize;
  imageUrl?: ImageURL;
  useUpload?: UseImageUpload;
  image?: UploadImageFile;
  data?: Images;
  [k: string]: unknown;
}
export interface UploadImageFile {
  [k: string]: unknown;
}
